'use strict';
function ankleActivity({id,label,motion,endAngle,endImage,endMoving,direction}){
 return {id,type:'scored',label,joint:'Ankle',motion,side:'Right',region:'ankle',proximal:'fibula',distal:'fifth metatarsal',typicalROM:endAngle,flexionDirection:direction,readingMode:'ankle-90',readingOffset:-90,hidePatientUntilPosition:true,
  positionLabel:'Supine or long sitting · knee extended · foot unsupported',scenario:`Measure right ankle AROM ${motion.toLowerCase()}. Identify the standard patient position before viewing the patient.`,axisName:'lateral malleolus',proximalReference:'lateral midline of the fibula toward the fibular head',distalReference:'lateral fifth metatarsal',
  description:`Close lateral medical render of the right lower leg and foot. The leg remains fixed while the entire foot moves into ankle ${motion.toLowerCase()}.`,poseCaption:`Approved lateral poses show neutral, dorsiflexion, and reduced plantarflexion with the lateral malleolus visible.`,motionInstruction:'Keep the knee and lower leg still. Move the entire foot at the ankle without inversion, eversion, or toe curling. Reposition the fulcrum and realign both arms.',placementGuide:'Center the fulcrum over the lateral malleolus. Align S with the lateral fibula and M with the fifth metatarsal.',visualStyle:'3d-medical-render',bodyView:'right-ankle-strict-lateral',startAngle:0,endAngle,readingTolerance:3,estimateTolerance:10,
  poses:[{image:'assets/ankle-neutral.png',angle:0,x:531,y:395,s:180,m:270,label:'Start · ankle neutral at 90°'},{image:endImage,angle:Math.round(endAngle/2),x:531,y:395,s:180,m:(270+direction*Math.round(endAngle/2)+360)%360,label:`Partway · moving toward ${motion.toLowerCase()}`},{image:endImage,angle:endAngle,x:531,y:395,s:180,m:endMoving,label:`Endpoint · ${motion}`}],
  visual:{image:'assets/ankle-neutral.png',x:0,y:55,width:800,height:530,clipAngle:0,neutralForearmRotation:0,forearmLengthScale:1,jointBlendRadius:30,referenceLength:205,overlayDuration:4500},axis:{targetX:531,targetY:395,tolerance:42},stationaryArm:{targetAngle:180,tolerance:15},movingArm:{targetAngle:270,tolerance:15},
  questions:[
   {skill:'patientPosition',title:'Choose the patient position',question:`What starting position is appropriate for ankle ${motion.toLowerCase()} in this activity?`,choices:['Supine or long sitting with the knee extended and foot unsupported','Standing with full weight on the tested foot','Prone with the toes pressed into the table','Sitting with the foot fixed flat on the floor'],correct:0,hint:'Choose a position that allows the foot to move freely while the lower leg remains stable.',explanation:'Use supine or long sitting with the knee extended and foot unsupported. The patient image is now shown.'},
   {skill:'axisKnowledge',title:'Identify the ankle axis',question:'Where should the fulcrum be centered?',choices:['Lateral malleolus','Base of the fifth metatarsal','Fibular head','Calcaneal tuberosity'],correct:0,hint:'Use the prominent outer ankle landmark.',explanation:'Center the fulcrum over the lateral malleolus.'},
   {skill:'stationaryArmKnowledge',title:'Identify the stationary reference',question:'Which reference should the stationary arm follow?',choices:['Lateral midline of the fibula toward the fibular head','Long axis of the foot','Anterior tibial crest','Perpendicular to the floor'],correct:0,hint:'Follow the lateral lower leg proximally.',explanation:'Align the stationary arm with the lateral midline of the fibula toward the fibular head.'},
   {skill:'movingArmKnowledge',title:'Identify the moving reference',question:'Which reference should the moving arm follow?',choices:['Lateral fifth metatarsal','Posterior calcaneus','Great toe','Medial tibia'],correct:0,hint:'Follow the lateral border of the foot.',explanation:'Align the moving arm parallel to the lateral fifth metatarsal.'},
   {skill:'zeroRecognition',title:'Establish zero and control compensation',question:'Which statement is correct?',choices:['The 90° foot-to-leg position is recorded as 0°; prevent inversion, eversion, and toe substitution','The foot hanging downward is 0°; inversion is allowed','Toe extension defines ankle zero','Knee flexion determines ankle zero'],correct:0,hint:'Goniometric neutral uses the right angle between the foot and lower leg.',explanation:'Record the 90-degree foot-to-leg position as neutral zero and prevent substitution.'}
  ],skills:[...ROM_ACTIVITIES[0].skills]};
}
ROM_ACTIVITIES.push(
 ankleActivity({id:'ankle-dorsiflexion',label:'Ankle Dorsiflexion',motion:'Dorsiflexion',endAngle:20,endImage:'assets/ankle-dorsiflexion.png',endMoving:250,direction:-1}),
 ankleActivity({id:'ankle-plantarflexion',label:'Ankle Plantarflexion',motion:'Plantarflexion',endAngle:45,endImage:'assets/ankle-plantarflexion.png',endMoving:315,direction:1})
);
