'use strict';
function hipRotation({id,label,motion,endAngle,endImage,endMoving,direction}){
 return {id,type:'scored',label,joint:'Hip',motion,side:'Right',region:'hip',proximal:'vertical reference',distal:'tibia',typicalROM:endAngle,flexionDirection:direction,readingMode:'overlap-zero',hidePatientUntilPosition:true,
  positionLabel:'Seated · hips and knees at 90° · thighs supported',scenario:`Measure right hip AROM ${motion.toLowerCase()}. Identify the standard patient position before viewing the patient.`,axisName:'anterior patella',proximalReference:'stationary arm perpendicular to the floor',distalReference:'anterior tibial crest toward the ankle',
  description:`Whole-patient medical render: seated upright with hips and knees flexed 90 degrees, thighs supported, and lower legs free. The right lower leg swings to produce hip ${motion.toLowerCase()} while the thigh and pelvis stay still.`,poseCaption:`Complete seated poses show neutral and hip ${motion.toLowerCase()}; the thigh and pelvis remain stable.`,motionInstruction:'Stabilize the pelvis and distal femur. Keep the thigh from abducting or adducting as the lower leg swings. Reposition the fulcrum and realign both arms.',placementGuide:'Center the fulcrum over the anterior patella. Keep S perpendicular to the floor and align M with the anterior tibial crest.',visualStyle:'3d-medical-render',bodyView:'whole-patient-seated-hip-rotation',startAngle:0,endAngle,readingTolerance:3,estimateTolerance:12,
  poses:[{image:'assets/hip-rotation-neutral.png',angle:0,x:285,y:315,s:90,m:90,label:'Start · lower leg vertical'},{image:endImage,angle:Math.round(endAngle/2),x:285,y:315,s:90,m:(90+direction*Math.round(endAngle/2)+360)%360,label:'Partway · thigh remains supported'},{image:endImage,angle:endAngle,x:285,y:315,s:90,m:endMoving,label:`Endpoint · ${motion}`}],
  visual:{image:'assets/hip-rotation-neutral.png',x:0,y:70,width:800,height:520,clipAngle:0,neutralForearmRotation:0,forearmLengthScale:1,jointBlendRadius:32,referenceLength:205,overlayDuration:4500},axis:{targetX:285,targetY:315,tolerance:42},stationaryArm:{targetAngle:90,tolerance:15},movingArm:{targetAngle:90,tolerance:15},
  questions:[
   {skill:'patientPosition',title:'Choose the patient position',question:`What is the standard starting position for seated hip ${motion.toLowerCase()} in this activity?`,choices:['Seated upright with hips and knees at 90°, thighs supported, lower legs free','Supine with both knees extended','Standing on the tested leg','Prone with the knee extended'],correct:0,hint:'Choose a position that supports the thigh while the lower leg can swing freely.',explanation:'Sit upright with hips and knees at 90 degrees, thighs supported, and lower legs free. The patient image is now shown.'},
   {skill:'axisKnowledge',title:'Identify the hip-rotation axis',question:'Where should the fulcrum be centered for this seated measurement?',choices:['Greater trochanter','Anterior patella','Tibial tuberosity','Medial malleolus'],correct:1,hint:'The goniometer is centered at the front of the knee for this indirect hip-rotation measure.',explanation:'Center the fulcrum over the anterior patella.'},
   {skill:'stationaryArmKnowledge',title:'Identify the stationary reference',question:'How should the stationary arm be aligned?',choices:['Along the femur','Perpendicular to the floor','Across the pelvis','Along the foot'],correct:1,hint:'Use a vertical environmental reference.',explanation:'Align the stationary arm perpendicular to the floor.'},
   {skill:'movingArmKnowledge',title:'Identify the moving reference',question:'Which reference should the moving arm follow?',choices:['Anterior tibial crest toward the ankle','Femur toward the hip','Fifth metatarsal','Midline of the trunk'],correct:0,hint:'Follow the front of the lower leg.',explanation:'Align the moving arm with the anterior tibial crest toward the ankle.'},
   {skill:'zeroRecognition',title:'Establish zero and control compensation',question:'Which statement is correct?',choices:['Lower leg vertical is 0°; stabilize the pelvis and thigh','Feet together is 0°; allow the thigh to move','Knee extension is 0°; pelvic motion is acceptable','Hip flexion is 0° in this seated setup'],correct:0,hint:'Start with the lower leg vertical and keep the thigh still.',explanation:'The vertical lower leg is zero. Prevent pelvic rotation and thigh abduction or adduction.'}
  ],skills:[...ROM_ACTIVITIES[0].skills]};
}
ROM_ACTIVITIES.push(
 hipRotation({id:'hip-internal-rotation',label:'Hip Internal Rotation',motion:'Internal Rotation',endAngle:40,endImage:'assets/hip-rotation-internal.png',endMoving:130,direction:1}),
 hipRotation({id:'hip-external-rotation',label:'Hip External Rotation',motion:'External Rotation',endAngle:45,endImage:'assets/hip-rotation-external.png',endMoving:45,direction:-1})
);
