'use strict';
const $=id=>document.getElementById(id), norm=a=>(a%360+360)%360;
const difference=(a,b)=>Math.abs(((a-b+540)%360)-180);
const point=(a,r)=>({x:Math.cos(a*Math.PI/180)*r,y:Math.sin(a*Math.PI/180)*r});
const stages=['Welcome','Position','Axis','Stationary arm','Moving arm','Place instrument','Starting zero','Visual estimate','Move & realign','Read scale','Document','Performance'];
const sessions={},history=[];
let cfg,state,drag=null,overlayTimer;
function fresh(c){return {stage:0,joint:0,instrument:{x:440,y:400,s:165,m:20},completed:{},inputs:{},measured:null,reading:0,number:(history.filter(h=>h.activity===c.id).length+1),records:Object.fromEntries(c.skills.map(k=>[k,{attempts:0,correct:null,hintUsed:false,answerRevealed:false,finalStatus:'Not assessed',phases:{},history:[]}]))};}
function choose(id,restart=false){clearTimeout(overlayTimer);drag=null;cfg=ROM_ACTIVITIES.find(c=>c.id===id);if(restart&&sessions[id])history.push(exportOne(cfg,sessions[id]));if(!sessions[id]||restart)sessions[id]=fresh(cfg);state=sessions[id];initializeAnatomy();render();$('task').focus();}
const scored=()=>cfg.type==='scored';
const direction=()=>cfg.flexionDirection??-1;
function pose(){return cfg.poses?cfg.poses.reduce((best,p)=>Math.abs(p.angle-state.joint)<Math.abs(best.angle-state.joint)?p:best,cfg.poses[0]):null;}
function targets(){const p=pose();return p?{x:p.x,y:p.y,s:p.s,m:p.m}:{x:cfg.axis.targetX,y:cfg.axis.targetY,s:cfg.stationaryArm.targetAngle,m:cfg.movingArm.targetAngle+direction()*state.joint};}
function renderPatientPose(){if(!cfg.poses)return;const p=pose();$('whole-patient-image').setAttribute('href',p.image);if(!cfg.hidePatientUntilPosition||state.completed[1])$('view-state').textContent=p.label;}

function updatePatientVisibility(){const hidden=!!cfg.hidePatientUntilPosition&&!state.completed[1];for(const id of ['patient-base','forearm'])$(id).setAttribute('visibility',hidden||cfg.poses?'hidden':'visible');$('whole-patient-image').setAttribute('visibility',cfg.poses&&!hidden?'visible':'hidden');$('position-cover').setAttribute('visibility',hidden?'visible':'hidden');$('scene-title').textContent=cfg.joint+' measurement workspace';$('scene-description').textContent=hidden?'Patient image withheld until the patient-position question is completed.':cfg.description;$('scene-caption').textContent=hidden?'Identify the standard patient position before viewing the patient.':cfg.poses?(cfg.poseCaption||'Whole-patient poses show the motion without separated or overlaid limb segments.'):'Medical-render right elbow workspace.';if(hidden)$('view-state').textContent='Position not yet selected';else if(cfg.poses)$('view-state').textContent=pose().label;else if(state.stage<=6)$('view-state').textContent=cfg.positionLabel;}
const question=()=>cfg.referenceQuizOnly?(state.stage>=2&&state.stage<=4?cfg.questions[state.stage-1]:null):(state.stage>=1&&state.stage<=4?cfg.questions[state.stage-1]:state.stage===6?cfg.questions[4]:null);
function phase(key){const r=state.records[key],s=state.stage;if(!r.phases[s])r.phases[s]={attempts:0,correct:null,hintUsed:false,answerRevealed:false,points:null};return r.phases[s];}
function useHint(key){const r=state.records[key],p=phase(key);r.hintUsed=p.hintUsed=true;if(p.points===2)p.points=1;if(scored())r.finalStatus='Needs Review';}
function record(key,ok,reveal=false){const r=state.records[key],p=phase(key);p.attempts++;r.attempts++;p.correct=r.correct=ok;p.answerRevealed ||= reveal;r.answerRevealed ||= reveal;p.points=p.answerRevealed?0:ok?(p.attempts===1&&!p.hintUsed?2:1):0;r.history.push({stage:state.stage,correct:ok,attempt:p.attempts,hintUsed:p.hintUsed,answerRevealed:p.answerRevealed});r.finalStatus=(scored()?points(key)===2:ok&&!r.answerRevealed)?'Competent':'Needs Review';}
function points(key,s=state){const p=Object.values(s.records[key].phases);return p.length?Math.min(...p.map(x=>x.points??0)):0;}
const assessedKeys=()=>cfg.assessedSkills||SCORE_KEYS;
function score(s=state){const keys=assessedKeys(),earned=keys.reduce((n,k)=>n+points(k,s),0);return {earned,possible:keys.length*2,percent:Math.round(earned/(keys.length*2)*100),independent:keys.filter(k=>points(k,s)===2).length};}
function feedback(html){$('feedback').innerHTML=html;}
function permit(){state.completed[state.stage]=true;if(state.stage===1)updatePatientVisibility();$('next').hidden=false;$('check').hidden=true;$('hint').hidden=true;}
function showOverlay(id){clearTimeout(overlayTimer);hideOverlays();$(id).setAttribute('visibility','visible');overlayTimer=setTimeout(hideOverlays,cfg.visual.overlayDuration);}
function hideOverlays(){for(const id of ['landmark','humerus-reference','radius-reference'])$(id).setAttribute('visibility','hidden');}
function answerOverlay(){if(scored())return;if(state.stage===2)showOverlay('landmark');if(state.stage===3)showOverlay('humerus-reference');if(state.stage===4)showOverlay('radius-reference');}
function initializeAnatomy(){const v=cfg.visual,a=cfg.axis;for(const id of ['base-image','forearm-image']){for(const k of ['x','y','width','height'])$(id).setAttribute(k,v[k]);$(id).setAttribute('href',v.image);}for(const id of ['landmark','base-cap','forearm-cap']){$(id).setAttribute('cx',a.targetX);$(id).setAttribute('cy',a.targetY);$(id).setAttribute('r',id==='landmark'?a.tolerance:v.jointBlendRadius);}for(const id of ['base-rect','forearm-rect']){$(id).setAttribute('y',-1000);$(id).setAttribute('height',2000);$(id).setAttribute('transform',`rotate(${v.clipAngle??0} ${a.targetX} ${a.targetY})`);}$('base-rect').setAttribute('x',-1000);$('base-rect').setAttribute('width',a.targetX+1000);$('forearm-rect').setAttribute('x',a.targetX);$('forearm-rect').setAttribute('width',2000);$('forearm-source').setAttribute('transform',`translate(${-a.targetX} ${-a.targetY})`);$('scene-description').textContent=cfg.description;$('anatomy-title').textContent=`Right ${cfg.region} · ${cfg.viewLabel||'lateral view'}`;$('scene-caption').textContent=scored()?'Medical-render patient workspace. Identify references and align the instrument independently.':'Medical-render right upper extremity. Identify landmarks through the questions; exact-point clicking is not required.';}
function alignment(){const i=state.instrument,t=targets();return {fulcrumPlacement:Math.hypot(i.x-t.x,i.y-t.y)<=cfg.axis.tolerance,stationaryArmAlignment:difference(i.s,t.s)<=cfg.stationaryArm.tolerance,movingArmAlignment:difference(i.m,t.m)<=cfg.movingArm.tolerance};}
function renderInstrument(){renderPatientPose();const i=state.instrument,v=cfg.visual,a=cfg.axis;$('forearm').setAttribute('transform',`translate(${a.targetX} ${a.targetY}) rotate(${v.neutralForearmRotation+direction()*state.joint}) scale(${v.forearmLengthScale} 1)`);for(const [id,angle] of [['humerus-reference',cfg.stationaryArm.targetAngle],['radius-reference',cfg.movingArm.targetAngle+direction()*state.joint]]){const p=point(angle,v.referenceLength);$(id).setAttribute('d',`M${a.targetX} ${a.targetY} l${p.x} ${p.y}`);}$('instrument').setAttribute('transform',`translate(${i.x} ${i.y})`);$('scale').innerHTML=scaleMarkup(i.s);$('stationary').innerHTML=armMarkup(i.s,'S','#164763');$('moving').innerHTML=armMarkup(i.m,'M','#007768');$('crosshair').setAttribute('d','M-10 0H10 M0 -10V10');
 if(state.stage===5||state.stage===8){const a=alignment();$('placement-prompt').textContent=scored()?'Align all three parts, then check placement.':!a.fulcrumPlacement?'1. Place the fulcrum over the lateral epicondyle.':!a.stationaryArmAlignment?'2. Rotate the stationary arm along the humerus.':!a.movingArmAlignment?'3. Rotate the moving arm along the radius.':'Alignment looks ready. Select Check placement.';}}
function instrumentReading(){const offset=cfg.readingOffset??(cfg.readingMode==='overlap-zero'?0:180);return norm(direction()*(state.instrument.m-state.instrument.s+offset));}
function renderCloseup(reveal=false){const reading=state.reading,d=direction(),m=point(d*reading,164),stationary=cfg.readingMode==='overlap-zero'?0:180;$('closeup').innerHTML=`<svg class="scale-closeup" viewBox="-190 ${d===1?-50:-190} 380 240" role="img" aria-label="Magnified scale: outer scale starts at zero along the stationary arm. Pointer at approximately ${Math.round(reading)} degrees on outer scale; approximately ${180-Math.round(reading)} on inner scale.">${scaleMarkup(stationary,reveal)}<path d="M-180 0H180" stroke="#164763" stroke-width="2"/><path d="M0 0L${m.x} ${m.y}" stroke="#007768" stroke-width="2"/><circle r="7" fill="white" stroke="#164763"/><text x="0" y="${d===1?-25:32}" text-anchor="middle" font-size="12" fill="#183746">S: stationary reference · green line: moving arm</text></svg>`;}
const numeric=label=>`<label for="numeric">${label}</label><input id="numeric" type="number" inputmode="decimal" min="0" max="180" step="1">`;
const skillLabel=key=>cfg.skillLabels?.[key]||SCORE_LABELS[key];
const motionName=()=>cfg.motion.toLowerCase();
const documented=()=>state.inputs[10]&&typeof state.inputs[10]==='object'?state.inputs[10]:null;
const documentationText=(start=cfg.startAngle,end=state.measured)=>`R ${cfg.region} AROM ${motionName()}: ${start}–${end}°`;
const documentationInputs=()=>`<fieldset class="documentation-entry"><legend>Enter both values</legend><label for="numeric-start">Starting position (degrees)<input id="numeric-start" type="number" inputmode="decimal" min="0" max="180" step="1"></label><span aria-hidden="true">to</span><label for="numeric-end">Endpoint (degrees)<input id="numeric-end" type="number" inputmode="decimal" min="0" max="180" step="1"></label></fieldset>`;
function profile(){const keys=assessedKeys(),total=score();let html=scored()?`<div class="score-card"><strong>${total.earned} / ${total.possible} points · ${total.percent}%</strong><p>${total.independent} of ${keys.length} skills demonstrated independently.</p></div><p>${total.independent===keys.length?'All assessed skills were independent in this attempt.':`Review the skills below, then start a new ${cfg.region} attempt to demonstrate independence.`}</p>`:'<p>Your tutorial performance does not count toward mastery.</p>';
 html+=`<table class="profile"><caption>${scored()?cfg.label+' Performance':'Tutorial Performance'}</caption><thead><tr><th scope="col">Skill</th><th scope="col">${scored()?'Points / status':'Status'}</th></tr></thead><tbody>${keys.map(k=>`<tr><th scope="row">${skillLabel(k)}</th><td>${scored()?`${points(k)}/2 · ${points(k)===2?'Independent':points(k)===1?'Supported':'Needs Review'}`:state.records[k].finalStatus}</td></tr>`).join('')}</tbody></table>`;
 if(scored())html+='<p class="small">Each skill earns 2 points for first-attempt success without a hint, 1 after help or a retry, and 0 after answer reveal. Placement uses the lower result from starting and endpoint checks. Visual estimation is formative. This is a practice score, not a course grade or clinical competency certification.</p>';
 if(!cfg.referenceQuizOnly){const doc=documented();html+=`<p class="callout">Recorded measurement: ${documentationText(doc?.start??cfg.startAngle,doc?.end??state.measured)}.</p>`;}html+=`<details><summary>Review hints and attempts</summary>${keys.map(k=>`<p><b>${skillLabel(k)}:</b> ${state.records[k].attempts} checks; hint ${state.records[k].hintUsed?'used':'not used'}; answer ${state.records[k].answerRevealed?'revealed':'not revealed'}.</p>`).join('')}</details><button id="download" class="secondary">Download session results</button> <button id="restart" class="secondary">${scored()?`New ${cfg.region} attempt`:'Restart tutorial'}</button>`;return html;}
function render(){clearTimeout(overlayTimer);hideOverlays();const st=state.stage,done=!!state.completed[st],q=question();$('mode-badge').textContent=scored()?`Scored practice · attempt ${state.number}`:'Tutorial · not graded';$('activity-name').textContent=scored()?cfg.label:'Tutorial: Elbow Flexion';for(const [button,id] of ACTIVITY_BUTTONS)$(button).setAttribute('aria-current',cfg.id===id?'step':'false');$('progress').textContent=`Step ${st+1} of ${stages.length}`;$('progress-bar').style.width=`${(st+1)/stages.length*100}%`;$('phase').textContent=`${scored()?'SCORED PRACTICE':'TUTORIAL'} · ${stages[st].toUpperCase()}`;$('stage-title').textContent=stages[st];feedback('');
 $('back').hidden=st===0||st===11;$('reset').hidden=![5,8].includes(st);$('hint').hidden=![1,2,3,4,5,6,8,9,10].includes(st)||done;$('check').hidden=![1,2,3,4,5,6,7,8,9,10].includes(st)||done;$('check').textContent=[5,8].includes(st)?'Check placement':st===7?'Save estimate':'Check answer';$('next').hidden=!done&&st!==0&&st!==11;$('next').textContent=st===0?'Begin':st===11?(scored()?`New ${cfg.region} attempt`:'Begin knee practice'):'Continue';$('manipulation').hidden=![5,8].includes(st);$('instrument').setAttribute('visibility',st>=5&&st!==7&&st!==11?'visible':'hidden');
 if(cfg.referenceQuizOnly)state.joint=st<=2?0:st===3?40:cfg.endAngle;else{if(st<=6)state.joint=0;if(st===7||st>=9)state.joint=cfg.endAngle;}$('view-state').textContent=cfg.referenceQuizOnly?pose().label:st===7?'Endpoint preview':st>=8?`Active ${motionName()}`:cfg.positionLabel;
 let html='';if(q){$('stage-title').textContent=q.title;html=`<p>${q.question}</p><fieldset class="choices"><legend class="small">Choose one answer, then check.</legend>${q.choices.map((c,i)=>`<label class="choice"><input type="radio" name="answer" value="${i}" ${state.inputs[st]===i?'checked':''} ${done?'disabled':''}><span>${c}</span></label>`).join('')}</fieldset>`;if(done)feedback(q.explanation);}
 else if(st===0){$('stage-title').textContent=scored()?cfg.label:'Tutorial: Measuring Elbow Flexion';if(cfg.referenceQuizOnly)html=`<p>${cfg.scenario}</p><p>Use the rotating right-front three-quarter images to identify the forearm axis, stationary reference, and moving reference.</p><div class="callout"><b>Reference-identification practice</b><p>Only these three multiple-choice skills are scored. Goniometer placement and placement scoring are removed.</p></div>`;else{html=`<p>${cfg.scenario}</p><p>Choose the position and anatomical references, place the instrument, establish zero, move the joint, realign, read, and document.</p>`;html+=scored()?'<div class="callout"><b>How this attempt is scored</b><p>10 skills × 2 points = 20 points. First-attempt success without hints earns 2; success after help or retry earns 1; answer reveal earns 0.</p></div>':'<div class="callout"><b>Your first instrument practice</b><p>This tutorial does not count toward mastery.</p></div>';}}
 else if(st===5){$('stage-title').textContent='Place the goniometer';html=`<p>${cfg.placementGuide}</p><p>Drag the ring and handles, or use the keyboard and arrow controls. Check all three parts before continuing.</p>`;}
 else if(st===7){$('stage-title').textContent='Estimate before you measure';html='<p>The image previews this patient’s endpoint. Make a broad visual estimate before using the scale.</p>'+numeric('Estimated ROM (degrees)')+'<p class="small">This estimate is formative and does not affect your score. Next, return to zero and move the limb yourself.</p>';}
 else if(st===8){$('stage-title').textContent='Move, then realign';html=`<p>Move the slider to <b>End</b>. ${cfg.poses?(cfg.motionInstruction||"Reposition the fulcrum and realign both instrument arms."):"Keep the "+cfg.proximal+" stable, then realign the instrument yourself."}</p><label for="joint-slider">${cfg.joint} movement</label><input id="joint-slider" type="range" min="0" max="${cfg.poses?2:100}" step="1" value="${cfg.poses?cfg.poses.indexOf(pose()):state.joint/cfg.endAngle*100}" aria-valuetext="Start position"><div class="range-labels"><span>Start</span>${cfg.poses?"<span>Partway</span>":""}<span>End</span></div><p>Recheck the fulcrum and both arms before continuing.</p>`;}
 else if(st===9){state.reading=instrumentReading();$('stage-title').textContent='Read the goniometer';html=`<p>${scored()?'Choose the correct scale and enter the instrument reading.':'Read the outer scale that begins at zero along the extension of the stationary arm.'}</p><div id="closeup"></div><button id="zoom" class="secondary">Enlarge scale</button>`+numeric(`Measured ${cfg.region} ${motionName()} ROM (degrees)`);}
 else if(st===10){$('stage-title').textContent='Document your measurement';html=`<p>Document the starting position and measured endpoint. Enter both values yourself.</p><div class="callout">Accepted endpoint scale reading: <b>${state.measured}°</b></div><p><b>R ${cfg.region} AROM ${motionName()}:</b></p>`+documentationInputs();}
 else if(st===11){$('stage-title').textContent=scored()?cfg.label+' Practice Complete':'Tutorial Complete';html=profile();}
 $('stage-content').innerHTML=html;if([7,9].includes(st)){if(state.inputs[st]!==undefined)$('numeric').value=state.inputs[st];$('numeric').disabled=done;}if(st===10){const doc=documented();if(doc){$('numeric-start').value=doc.start;$('numeric-end').value=doc.end;}$('numeric-start').disabled=done;$('numeric-end').disabled=done;}
 if(st===8){$('joint-slider').setAttribute('aria-valuetext',state.joint===cfg.endAngle?'Endpoint':state.joint===0?'Start position':'Moving toward endpoint');$('joint-slider').oninput=e=>{state.joint=cfg.poses?cfg.poses[Number(e.target.value)].angle:Number(e.target.value)/100*cfg.endAngle;e.target.setAttribute('aria-valuetext',state.joint===cfg.endAngle?'Endpoint':state.joint===0?'Start position':'Partway');invalidatePlacement();renderInstrument();};}
 if(st===9){renderCloseup(state.records.scaleReading.answerRevealed);$('zoom').onclick=()=>{$('zoom-scale').innerHTML=$('closeup').innerHTML;$('scale-dialog').showModal();};}
 if(st===11){$('download').onclick=download;$('restart').onclick=()=>choose(cfg.id,true);}renderInstrument();updatePatientVisibility();}
function invalidatePlacement(){if(![5,8].includes(state.stage))return;for(let s=state.stage;s<12;s++){delete state.completed[s];if(s>=9)delete state.inputs[s];}state.measured=null;$('next').hidden=true;$('check').hidden=false;$('hint').hidden=false;feedback('');}
function placementHint(){return `Center the fulcrum at the ${cfg.axisName}. Align S with the ${cfg.proximalReference}, and M with the ${cfg.distalReference}.`;}
function placementCheck(){if(state.stage===8&&state.joint<cfg.endAngle){feedback(`Move the ${cfg.region} fully to End, then realign before checking.`);return;}const checks=alignment();let html='';for(const [k,ok] of Object.entries(checks)){const p=phase(k);if(!(ok&&p.correct===true)){record(k,ok,!ok&&p.attempts>=1);}html+=`<p><b>${SCORE_LABELS[k]}:</b> ${ok?'Correct':'Needs correction'}</p>`;}
 if(Object.values(checks).every(Boolean)){feedback(html+'<p>Placement checked. Continue when ready.</p>');permit();}else{const reveal=Object.keys(checks).some(k=>!checks[k]&&phase(k).answerRevealed);Object.keys(checks).filter(k=>!checks[k]).forEach(useHint);feedback(html+(reveal?`<p>Reference: ${placementHint()} Reposition the incorrect parts yourself, then check again.</p>`:'<p>Hint: Recheck the indicated part against its anatomical reference. Adjust it and try again.</p>'));if(reveal&&!scored())showOverlay('landmark');}}
function check(){if(state.completed[state.stage])return;const q=question();if(q){const selected=document.querySelector('input[name="answer"]:checked');if(!selected){feedback('Select one answer first.');return;}const v=Number(selected.value),p=phase(q.skill),ok=v===q.correct;state.inputs[state.stage]=v;record(q.skill,ok,!ok&&p.attempts>=1);if(ok||p.answerRevealed){feedback(`${ok?'Correct.':'Answer: '+q.choices[q.correct]+'.'} ${q.explanation}`);document.querySelectorAll('input[name="answer"]').forEach(e=>e.disabled=true);permit();answerOverlay();}else{useHint(q.skill);feedback('Hint: '+q.hint+' Try once more.');}return;}
 if([5,8].includes(state.stage)){placementCheck();return;}if(state.stage===10){const startInput=$('numeric-start'),endInput=$('numeric-end');if(!startInput||!endInput||startInput.value.trim()===''||endInput.value.trim()===''||!startInput.checkValidity()||!endInput.checkValidity()){feedback('Enter both the starting position and endpoint as whole numbers from 0 to 180 degrees.');return;}const values={start:Number(startInput.value),end:Number(endInput.value)},p=phase('documentation'),ok=values.start===cfg.startAngle&&values.end===state.measured;state.inputs[10]=values;record('documentation',ok,!ok&&p.attempts>=1);if(ok||p.answerRevealed){if(!ok){state.inputs[10]={start:cfg.startAngle,end:state.measured};startInput.value=cfg.startAngle;endInput.value=state.measured;}feedback(`${ok?'Documentation accepted.':'Use the measured starting position and endpoint.'} ${documentationText()}.`);startInput.disabled=endInput.disabled=true;permit();}else{useHint('documentation');feedback('Hint: Enter the measured starting position in the first field and the accepted endpoint in the second field. Try once more.');}return;}const input=$('numeric');if(!input||input.value.trim()===''||!input.checkValidity()){feedback('Enter a whole number from 0 to 180 degrees.');return;}const v=Number(input.value);state.inputs[state.stage]=v;
 if(state.stage===7){record('visualEstimate',Math.abs(v-cfg.endAngle)<=cfg.estimateTolerance);feedback('Estimate recorded. Compare it with the precise instrument reading later.');input.disabled=true;permit();return;}
 const p=phase('scaleReading'),ok=Math.abs(v-state.reading)<=cfg.readingTolerance;record('scaleReading',ok,!ok&&p.attempts>=1);if(ok||p.answerRevealed){state.measured=ok?v:Math.round(state.reading);feedback(ok?'Reading accepted. Continue to documentation.':`The instrument reads approximately ${Math.round(state.reading)}°. Follow the highlighted outer scale.`);if(!ok)renderCloseup(true);input.disabled=true;permit();}else{useHint('scaleReading');feedback('Hint: Trace the moving-arm line to the scale whose zero follows the extension of the stationary arm. Try once more.');}}
function hint(){const q=question();if(q){useHint(q.skill);feedback(q.hint);}else if([5,8].includes(state.stage)){Object.keys(alignment()).forEach(useHint);feedback(placementHint());if(!scored()&&state.completed[2])showOverlay('landmark');}else{const key=state.stage===9?'scaleReading':'documentation';useHint(key);feedback(state.stage===9?'Choose the scale that begins at zero along the extension of the stationary arm. Trace the moving-arm line to its tick.':'Enter both the measured starting position and accepted endpoint.');}}
function adjust(part,dir){if(![5,8].includes(state.stage))return;const i=state.instrument,d=dir==='right'||dir==='up'?1:-1;if(part==='center'){if(dir==='left')i.x-=5;if(dir==='right')i.x+=5;if(dir==='up')i.y-=5;if(dir==='down')i.y+=5;i.x=Math.max(180,Math.min(610,i.x));i.y=Math.max(185,Math.min(430,i.y));}else i[part]=norm(i[part]+d);invalidatePlacement();renderInstrument();}
function exportOne(c,s){return {activity:c.id,type:c.type,attempt:s.number,completed:!!s.completed[10],countsTowardPracticeMastery:c.type==='scored',measurement:s.measured,documentation:s.inputs[10]??null,score:c.type==='scored'?score(s):null,skills:JSON.parse(JSON.stringify(s.records))};}
function download(){const payload={schemaVersion:2,scope:'Local practice; not an LMS grade',rule:'2 independent first attempt; 1 after hint/retry; 0 after reveal; lowest placement phase per skill',previousAttempts:history,currentActivities:Object.entries(sessions).map(([id,s])=>exportOne(ROM_ACTIVITIES.find(c=>c.id===id),s))};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='rom-lab-session-results.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function localPoint(e){return new DOMPoint(e.clientX,e.clientY).matrixTransform($('scene').getScreenCTM().inverse());}
const scene=$('scene');scene.addEventListener('pointerdown',e=>{if(![5,8].includes(state.stage)||!e.target.dataset.part)return;const p=localPoint(e);drag={part:e.target.dataset.part,id:e.pointerId,dx:p.x-state.instrument.x,dy:p.y-state.instrument.y};scene.setPointerCapture(e.pointerId);e.preventDefault();});scene.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const p=localPoint(e),i=state.instrument;if(drag.part==='center'){i.x=Math.max(180,Math.min(610,p.x-drag.dx));i.y=Math.max(185,Math.min(430,p.y-drag.dy));}else i[drag.part]=norm(Math.atan2(p.y-i.y,p.x-i.x)*180/Math.PI);invalidatePlacement();renderInstrument();});
function release(e){if(drag&&e.pointerId===drag.id){drag=null;if(scene.hasPointerCapture(e.pointerId))scene.releasePointerCapture(e.pointerId);}}scene.addEventListener('pointerup',release);scene.addEventListener('pointercancel',release);scene.addEventListener('lostpointercapture',()=>drag=null);
$('keyboard').onkeydown=e=>{const dirs={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'};if(dirs[e.key]){e.preventDefault();adjust(e.ctrlKey?'m':e.shiftKey?'s':'center',dirs[e.key]);}};document.querySelectorAll('[data-nudge]').forEach(b=>b.onclick=()=>adjust($('part').value,b.dataset.nudge));$('check').onclick=check;$('hint').onclick=hint;
const ACTIVITY_BUTTONS=[['module-elbow','elbow-flexion'],['module-knee','knee-flexion'],['module-shoulder','shoulder-flexion'],['module-pronation','forearm-pronation'],['module-supination','forearm-supination'],['module-shoulder-ir','shoulder-internal-rotation'],['module-shoulder-er','shoulder-external-rotation'],['module-hip-ir','hip-internal-rotation'],['module-hip-er','hip-external-rotation'],['module-ankle-df','ankle-dorsiflexion'],['module-ankle-pf','ankle-plantarflexion']];
$('next').onclick=()=>{if(state.stage===11){choose(scored()?cfg.id:'knee-flexion',scored());return;}if(state.stage>0&&!state.completed[state.stage])return;if(cfg.referenceQuizOnly){state.stage=state.stage===0?2:state.stage===4?11:state.stage+1;render();$('task').focus();return;}if(state.stage===7){state.joint=0;for(let s=8;s<12;s++)delete state.completed[s];state.measured=null;delete state.inputs[9];delete state.inputs[10];}state.stage++;render();$('task').focus();};$('back').onclick=()=>{if(state.stage>0){state.stage=cfg.referenceQuizOnly?(state.stage===11?4:state.stage===2?0:state.stage-1):state.stage-1;render();$('task').focus();}};$('reset').onclick=()=>{state.instrument={x:440,y:400,s:165,m:20};invalidatePlacement();renderInstrument();};for(const [button,id] of ACTIVITY_BUTTONS)$(button).onclick=()=>choose(id);$('close-scale').onclick=()=>$('scale-dialog').close();
// Shared SVG instrument renderer appended below.
function scaleMarkup(s,reveal=false){const dir=direction(),zero=cfg.readingMode==='overlap-zero'?0:180,rotation=s-zero;let out=`<g transform="rotate(${rotation})"><path d="M-166 0 A166 166 0 0 ${dir===-1?1:0} 166 0 L0 0Z" fill="#f7fcff" fill-opacity=".87" stroke="#305c70" stroke-width="2"/>`;
 for(let d=0;d<=180;d++){const p=point(dir*d,164),t=point(dir*d,d%10===0?148:d%5===0?154:159);out+=`<path d="M${p.x} ${p.y}L${t.x} ${t.y}" stroke="#183746" stroke-width="${d%10===0?1.8:.8}"/>`;if(d%10===0){const a=point(dir*d,135),b=point(dir*d,111);out+=`<text x="${a.x}" y="${a.y}" text-anchor="middle" dominant-baseline="middle" font-size="12" font-weight="700" fill="${reveal?'#005b4f':'#183746'}" transform="rotate(${-rotation} ${a.x} ${a.y})">${d}</text><text x="${b.x}" y="${b.y}" text-anchor="middle" dominant-baseline="middle" font-size="10" fill="#52646f" transform="rotate(${-rotation} ${b.x} ${b.y})">${180-d}</text>`;}}
 return out+'</g>';}
function armMarkup(angle,label,color){const length=cfg.readingMode==='overlap-zero'&&label==='S'?190:240,p=point(angle,length),h=point(angle,length-22);return `<path d="M0 0 L${p.x} ${p.y}" stroke="${color}" stroke-opacity=".2" stroke-width="28"/><path d="M0 0 L${p.x} ${p.y}" stroke="${color}" stroke-width="2.5"/><circle data-part="${label==='S'?'s':'m'}" cx="${h.x}" cy="${h.y}" r="23" fill="white" stroke="${color}" stroke-width="3"/><text x="${h.x}" y="${h.y+6}" text-anchor="middle" font-size="18" font-weight="700" fill="${color}" pointer-events="none">${label}</text>`;}

$('whole-patient-image').addEventListener('error',()=>feedback('The patient image could not load. Keep the assets folder beside index.html, then reopen the activity.'));
if(typeof Image!=='undefined')for(const c of ROM_ACTIVITIES)for(const p of c.poses??[]){const img=new Image();img.src=p.image;}
choose('elbow-flexion');

