'use strict';
function shoulderRotation({id,label,motion,endAngle,endImage,endMoving,direction}){
 return {id,type:'scored',label,joint:'Shoulder',motion,side:'Right',region:'shoulder',proximal:'humerus',distal:'ulna',typicalROM:endAngle,flexionDirection:direction,readingMode:'overlap-zero',hidePatientUntilPosition:true,
  positionLabel:'Supine · shoulder abducted 90° · elbow flexed 90°',scenario:`Measure right shoulder AROM ${motion.toLowerCase()}. Identify the standard patient position before viewing the patient.`,
  axisName:'olecranon process',proximalReference:'stationary arm perpendicular to the floor',distalReference:'ulna toward the ulnar styloid',
  description:`Whole-patient medical render: supine with the right shoulder abducted 90 degrees, elbow flexed 90 degrees, and upper arm supported. The forearm moves into shoulder ${motion.toLowerCase()} while the scapula and trunk remain controlled.`,
  poseCaption:`Complete whole-patient poses show neutral and ${motion.toLowerCase()} without a duplicated or floating arm.`,motionInstruction:'Keep the upper arm supported and shoulder at 90° abduction. Prevent scapular lift, trunk rotation, and lumbar extension. Reposition the fulcrum and realign both arms.',
  placementGuide:'Center the fulcrum over the olecranon. Keep S perpendicular to the floor and align M with the ulna toward the ulnar styloid.',visualStyle:'3d-medical-render',bodyView:'whole-patient-supine-shoulder-rotation',startAngle:0,endAngle,readingTolerance:3,estimateTolerance:15,
  poses:[{image:'assets/shoulder-rotation-neutral.png',angle:0,x:426,y:435,s:270,m:270,label:'Start · forearm vertical in neutral'},{image:endImage,angle:Math.round(endAngle/2),x:426,y:435,s:270,m:(270+direction*Math.round(endAngle/2)+360)%360,label:'Partway · control scapular motion'},{image:endImage,angle:endAngle,x:426,y:435,s:270,m:endMoving,label:`Endpoint · ${motion}`}],
  visual:{image:'assets/shoulder-rotation-neutral.png',x:0,y:75,width:800,height:500,clipAngle:0,neutralForearmRotation:0,forearmLengthScale:1,jointBlendRadius:32,referenceLength:205,overlayDuration:4500},axis:{targetX:426,targetY:435,tolerance:42},stationaryArm:{targetAngle:270,tolerance:15},movingArm:{targetAngle:270,tolerance:15},
  questions:[
   {skill:'patientPosition',title:'Choose the patient position',question:`What is the standard starting position for shoulder ${motion.toLowerCase()} in this activity?`,choices:['Supine, shoulder abducted 90°, elbow flexed 90°, upper arm supported, forearm vertical','Standing with the arm at the side and elbow extended','Prone with the arm behind the back','Sidelying on the tested shoulder'],correct:0,hint:'Choose the supported position that places the humerus at 90 degrees of abduction and lets the forearm rotate.',explanation:'Use supine with the shoulder abducted and elbow flexed to 90 degrees. Support the upper arm and begin with the forearm vertical. The patient image is now shown.'},
   {skill:'axisKnowledge',title:'Identify the shoulder-rotation axis',question:'Where should the fulcrum be centered?',choices:['Acromion','Olecranon process','Lateral epicondyle','Radial styloid'],correct:1,hint:'Use the posterior elbow landmark at the center of forearm rotation.',explanation:'Center the fulcrum over the olecranon process.'},
   {skill:'stationaryArmKnowledge',title:'Identify the stationary reference',question:'How should the stationary arm be aligned?',choices:['Along the humerus','Perpendicular to the floor','Along the trunk','Across the clavicle'],correct:1,hint:'The stationary reference is environmental rather than a long bone.',explanation:'Align the stationary arm perpendicular to the floor.'},
   {skill:'movingArmKnowledge',title:'Identify the moving reference',question:'Which reference should the moving arm follow?',choices:['Ulna toward the ulnar styloid','Radius toward the thumb','Humerus toward the shoulder','Midline of the sternum'],correct:0,hint:'Follow the forearm on the little-finger side.',explanation:'Align the moving arm with the ulna toward the ulnar styloid.'},
   {skill:'zeroRecognition',title:'Establish zero and control compensation',question:'Which statement is correct?',choices:['Forearm vertical is 0°; control scapular lift, trunk rotation, and lumbar extension','Forearm on the table is 0°; allow the scapula to lift','Elbow extension is 0°; trunk motion does not matter','Arm at the side is 0° for this setup'],correct:0,hint:'Start with the forearm vertical and keep the scapula and trunk stable.',explanation:'The vertical forearm is the zero position for this setup. Stop when scapular or trunk compensation begins.'}
  ],skills:[...ROM_ACTIVITIES[0].skills]};
}
ROM_ACTIVITIES.push(
 shoulderRotation({id:'shoulder-internal-rotation',label:'Shoulder Internal Rotation',motion:'Internal Rotation',endAngle:90,endImage:'assets/shoulder-rotation-internal.png',endMoving:0,direction:1}),
 shoulderRotation({id:'shoulder-external-rotation',label:'Shoulder External Rotation',motion:'External Rotation',endAngle:90,endImage:'assets/shoulder-rotation-external.png',endMoving:180,direction:-1})
);
